# Generated by Django 4.1.2 on 2022-10-20 19:15

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('energy', models.CharField(max_length=255)),
                ('dry_matter', models.CharField(max_length=255)),
                ('proteins', models.CharField(max_length=255)),
                ('total_fat', models.CharField(max_length=255)),
                ('ash', models.CharField(max_length=255)),
                ('crude_fiber', models.CharField(max_length=255)),
                ('carbohydrate', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='product_imgs/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saraeurope.products')),
            ],
        ),
    ]
