# Generated by Django 4.1.2 on 2022-11-10 15:29

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('context', ckeditor_uploader.fields.RichTextUploadingField()),
                ('context_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('context_bs', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('context_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('context_de', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
            ],
            options={
                'verbose_name': 'About Us',
                'verbose_name_plural': 'About Us',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('category_en', models.CharField(blank=True, max_length=255, null=True)),
                ('category_bs', models.CharField(blank=True, max_length=255, null=True)),
                ('category_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('category_de', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Slider', 'Slider'), ('Gallery', 'Gallery')], max_length=255)),
                ('picture', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor_uploader.fields.RichTextUploadingField()),
                ('description_en', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_bs', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_ru', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('description_de', ckeditor_uploader.fields.RichTextUploadingField(null=True)),
                ('energy', models.CharField(max_length=255)),
                ('dry_matter', models.CharField(max_length=255)),
                ('proteins', models.CharField(max_length=255)),
                ('total_fat', models.CharField(max_length=255)),
                ('ash', models.CharField(max_length=255)),
                ('crude_fiber', models.CharField(max_length=255)),
                ('carbohydrate', models.CharField(max_length=255)),
                ('img', models.FileField(blank=True, upload_to='')),
                ('filter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='saraeurope.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='product_imgs/')),
                ('product', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='saraeurope.products')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
    ]
