# Generated by Django 4.1.2 on 2022-11-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraeurope', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=255)),
            ],
        ),
    ]
