# Generated by Django 4.1.2 on 2022-11-08 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saraeurope', '0002_products_description_bs_products_description_de_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pictures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('Slider', 'Slider'), ('Gallery', 'Gallery')], max_length=255)),
                ('picture', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name': 'Picture',
                'verbose_name_plural': 'Pictures',
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
        migrations.AlterModelOptions(
            name='products',
            options={'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.RemoveField(
            model_name='products',
            name='title_bs',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title_de',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='products',
            name='title_ru',
        ),
    ]
